### PR TITLE
fix(query): use executeCtx in newResult (fixes #2081)

### LINKED ISSUE #2081: bug: flaky integration test ExecuteDataQuery
# Bug Report

**YDB GO SDK version:**

**Environment**

**Current behavior:**

```
--- FAIL: TestBasicExampleQuery (0.19s)
    --- FAIL: TestBasicExampleQuery/ExecuteDataQuery (0.00s)
        basic_example_query_test.go:392: 
            	Error Trace:	/home/runner/work/ydb-go-sdk/ydb-go-sdk/tests/integration/basic_example_query_test.go:392
            	Error:      	Received unexpected error:
            	            	pool.With failed with 1 attempts: non-retryable error occurred on attempt No.1 (idempotent=false): context canceled at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.newResult(result.go:169)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.execute(execute_query.go:146)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.(*Session).execute(session.go:176)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.(*Session).queryRow(session.go:70)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.clientQueryRow.func1(client.go:330)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.do.func1(client.go:224)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/pool.(*Pool).try(pool.go:484)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/pool.(*Pool).With.func2(pool.go:512)` at `github.com/ydb-platform/ydb-go-sdk/v3/retry.Retry.func1(retry.go:264)` at `github.com/ydb-platform/ydb-go-sdk/v3/retry.opWithRecover(retry.go:418)` at `github.com/ydb-platform/ydb-go-sdk/v3/retry.RetryWithResult(retry.go:358)` at `github.com/ydb-platform/ydb-go-sdk/v3/retry.Retry(retry.go:270)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/pool.(*Pool).With(pool.go:518)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.do(client.go:232)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.clientQueryRow(client.go:336)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.(*Client).QueryRow(client.go:362)`
            	Test:       	TestBasicExampleQuery/ExecuteDataQuery
    basic_example_query_test.go:47: total consumed units: 46
    mutex.go:15: 
```

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

### PR DESCRIPTION
**Pull request by kprokopenko**
## Summary
Fixes flaky `TestBasicExampleQuery/ExecuteDataQuery` and incorrect non-retry behavior for idempotent queries when the session-scoped context is done while the gRPC stream is still open.

## Root cause
- `execute` opens the stream with `executeCtx` (decoupled via `xcontext.ValueOnly` + `WithCancel`, with parent cancellation wired via `context.AfterFunc(ctx, executeCancel)`).
- `newResult` was called with the parent `ctx` (includes session `WithDone`). The early `select` on `ctx.Done()` in `newResult` could return `context.Canceled` before any `Recv`, and retry classifies that as non-retryable.

## Change
- Pass `executeCtx` to `newResult`, consistent with `ExecuteQuery` and the stream lifetime.

## Changelog
- User-facing entry under v3.135.1

Closes #2081

Made with [Cursor](https://cursor.com)

### CODE REVIEW

**Review by asmyasnikov — APPROVED** [review]

**Comment by asmyasnikov** [comment]
@copilot  добавьте тесты для изменений в PR
тест должен быть красным до фиксации и зеленым после

**Review by asmyasnikov — APPROVED** [review]

**Comment by asmyasnikov** [comment]
@copilot есть поломанные тесты
1) go 1.21, ubuntu
```
=== RUN   TestExecute/ContextCancellation/CancelParentContextAfterStreamOpen
    execute_query_test.go:537: 
        	Error Trace:	/home/runner/work/ydb-go-sdk/ydb-go-sdk/internal/query/execute_query_test.go:537
        	Error:      	Received unexpected error:
        	            	'context canceled' at `runtime.goexit(asm_amd64.s:1700)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.newResult(result.go:165)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.execute(execute_query.go:148)`
        	Test:       	TestExecute/ContextCancellation/CancelParentContextAfterStreamOpen
    controller.go:98: missing call(s) to *query.MockQueryService_ExecuteQueryClient.Recv() /home/runner/work/ydb-go-sdk/ydb-go-sdk/internal/query/execute_query_test.go:513
    controller.go:98: missing call(s) to *query.MockQueryService_ExecuteQueryClient.Recv() /home/runner/work/ydb-go-sdk/ydb-go-sdk/internal/query/execute_query_test.go:521
    controller.go:98: aborting test due to missing call(s)
--- FAIL: TestExecute (0.01s)
    --- PASS: TestExecute/HappyWay (0.00s)
    --- PASS: TestExecute/TransportError (0.00s)
        --- PASS: TestExecute/TransportError/OnCall (0.00s)
        --- PASS: TestExecute/TransportError/OnStream (0.00s)
    --- PASS: TestExecute/OperationError (0.00s)
        --- PASS: TestExecute/OperationError/OnCall (0.00s)
        --- PASS: TestExecute/OperationError/OnStream (0.00s)
    --- FAIL: TestExecute/ContextCancellation (0.00s)
        --- PASS: TestExecute/ContextCancellation/CancelWhileExecute (0.00s)
        --- PASS: TestExecute/ContextCancellation/CancelAfterExecute (0.00s)
        --- FAIL: TestExecute/ContextCancellation/CancelParentContextAfterStreamOpen (0.00s)
```
2) go 1.26, ubuntu
```
--- FAIL: TestBasicExampleQuery (0.17s)
    --- FAIL: TestBasicExampleQuery/ExecuteDataQuery (0.00s)
        basic_example_query_test.go:392: 
            	Error Trace:	/home/runner/work/ydb-go-sdk/ydb-go-sdk/tests/integration/basic_example_query_test.go:392
            	Error:      	Received unexpected error:
            	            	pool.With failed with 1 attempts: non-retryable error occurred on attempt No.1 (idempotent=false): stream context is done: ["rpc error: code = Canceled desc = context canceled","'context canceled' at `runtime.goexit(asm_amd64.s:1771)`"] at `github.com/ydb-platform/ydb-go-sdk/v3/internal/conn.(*grpcClientStream).RecvMsg(grpc_client_stream.go:155)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.nextPart(result.go:241)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.(*streamResult).nextPart(result.go:219)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.newResult(result.go:169)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.execute(execute_query.go:148)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.(*Session).execute(session.go:176)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.(*Session).queryRow(session.go:70)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.clientQueryRow.func1(client.go:330)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.do.func1(client.go:224)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/pool.(*Pool).try(pool.go:490)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/pool.(*Pool).With.func2(pool.go:518)` at `github.com/ydb-platform/ydb-go-sdk/v3/retry.Retry.func1(retry.go:264)` at `github.com/ydb-platform/ydb-go-sdk/v3/retry.opWithRecover(retry.go:418)` at `github.com/ydb-platform/ydb-go-sdk/v3/retry.RetryWithResult(retry.go:358)` at `github.com/ydb-platform/ydb-go-sdk/v3/retry.Retry(retry.go:270)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/pool.(*Pool).With(pool.go:524)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.do(client.go:232)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.clientQueryRow(client.go:336)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.(*Client).QueryRow(client.go:362)`
            	Test:       	TestBasicExampleQuery/ExecuteDataQuery
    basic_example_query_test.go:47: total consumed units: 36
    mutex.go:15: 
        
```
3) go 1.26, windows
```
=== RUN   TestExecute/ContextCancellation/CancelParentContextAfterStreamOpen
    execute_query_test.go:537: 
        	Error Trace:	D:/a/ydb-go-sdk/ydb-go-sdk/internal/query/execute_query_test.go:537
        	Error:      	Received unexpected error:
        	            	'context canceled' at `runtime.goexit(asm_amd64.s:1771)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.(*streamResult).nextPart(result.go:194)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.newResult(result.go:169)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.execute(execute_query.go:148)`
        	Test:       	TestExecute/ContextCancellation/CancelParentContextAfterStreamOpen
    controller.go:98: missing call(s) to *query.MockQueryService_ExecuteQueryClient.Recv() D:/a/ydb-go-sdk/ydb-go-sdk/internal/query/execute_query_test.go:513
    controller.go:98: missing call(s) to *query.MockQueryService_ExecuteQueryClient.Recv() D:/a/ydb-go-sdk/ydb-go-sdk/internal/query/execute_query_test.go:521
    controller.go:98: aborting test due to missing call(s)
--- FAIL: TestExecute (0.00s)
    --- PASS: TestExecute/HappyWay (0.00s)
    --- PASS: TestExecute/TransportError (0.00s)
        --- PASS: TestExecute/TransportError/OnCall (0.00s)
        --- PASS: TestExecute/TransportError/OnStream (0.00s)
    --- PASS: TestExecute/OperationError (0.00s)
        --- PASS: TestExecute/OperationError/OnCall (0.00s)
        --- PASS: TestExecute/OperationError/OnStream (0.00s)
    --- FAIL: TestExecute/ContextCancellation (0.00s)
        --- PASS: TestExecute/ContextCancellation/CancelWhileExecute (0.00s)
        --- PASS: TestExecute/ContextCancellation/CancelAfterExecute (0.00s)
        --- FAIL: TestExecute/ContextCancellation/CancelParentContextAfterStreamOpen (0.00s)
```

File: internal/query/execute_query_test.go [hunk 1]
```diff
@@ -498,6 +499,97 @@ func TestExecute(t *testing.T) {
...
+}
+
+// TestNewResult_DecoupledExecuteCtx verifies the semantic contract that
+// newResult succeeds when passed executeCtx (derived from a cancelled parent
+// via xcontext.ValueOnly), which is exactly what execute() does after the fix
+// for https://github.com/ydb-platform/ydb-go-sdk/issues/2081.
+func TestNewResult_DecoupledExecuteCtx(t *testing.T) {
+	t.Run("CancelledParentCtxCausesImmediateError", func(t *testing.T) {
+		// With the parent ctx passed directly, a cancelled ctx makes newResult
+		// fail before it ever calls Recv(). This is the old (buggy) behaviour
```
Comment (asmyasnikov) [inline internal/query/execute_query_test.go]:
```suggestion
		// fail before it ever calls Recv(). This is the old (buggy) behavior
```

File: internal/query/execute_query_test.go [hunk 2]
```diff
@@ -498,6 +499,97 @@ func TestExecute(t *testing.T) {
...
+			// Recv must NOT be called: execute() returns a retryable error before
+			// reaching newResult because stop() detects the AfterFunc was already started.
+			stream := NewMockQueryService_ExecuteQueryClient(ctrl)
+
+			client := NewMockQueryServiceClient(ctrl)
+			client.EXPECT().ExecuteQuery(gomock.Any(), gomock.Any()).DoAndReturn(
+				func(_ context.Context, _ *Ydb_Query.ExecuteQueryRequest, _ ...grpc.CallOption) (
+					Ydb_Query_V1.QueryService_ExecuteQueryClient, error,
+				) {
+					// Simulate session expiry: cancelling ctx starts the AfterFunc goroutine.
```
Comment (asmyasnikov) [inline internal/query/execute_query_test.go]:
```suggestion
					// Simulate session expiry: canceling ctx starts the AfterFunc goroutine.
```

File: internal/query/execute_query.go [hunk 3]
```diff
@@ -124,6 +124,8 @@ func execute(
 
 	executeCtx, executeCancel := xcontext.WithCancel(xcontext.ValueOnly(ctx))
 
+	// AfterFunc propagates parent cancellation to executeCtx during ExecuteQuery,
+	// ensuring the gRPC call honours ctx's lifetime (e.g. user cancel, deadline).
```
Comment (asmyasnikov) [inline internal/query/execute_query.go]:
```suggestion
	// ensuring the gRPC call honors ctx's lifetime (e.g. user cancel, deadline).
```

File: internal/query/execute_query_test.go [hunk 4]
```diff
@@ -498,6 +499,97 @@ func TestExecute(t *testing.T) {
...
 		})
+
+		// Regression test for https://github.com/ydb-platform/ydb-go-sdk/issues/2081.
+		//
+		// When the parent ctx is cancelled inside ExecuteQuery (simulating session expiry
+		// while the gRPC stream is still open), the AfterFunc goroutine that propagates
+		// the cancellation to executeCtx is guaranteed to have been started by the time
+		// stop() is called. execute() must detect this via stop() returning false and
+		// return a retryable error — not a non-retryable context.Canceled — so the pool
+		// can retry with a new session.
```
[the remark this answers is not in the document]
Comment (asmyasnikov) [reply internal/query/execute_query_test.go]: @copilot apply changes based on [this feedback](https://github.com/ydb-platform/ydb-go-sdk/pull/2100#discussion_r3160411159)

**Comment by asmyasnikov** [comment]
@copilot все еще есть сломаные тесты
```
--- FAIL: TestBasicExampleQuery (0.18s)
    --- FAIL: TestBasicExampleQuery/ExecuteDataQuery (0.00s)
        basic_example_query_test.go:392: 
            	Error Trace:	/home/runner/work/ydb-go-sdk/ydb-go-sdk/tests/integration/basic_example_query_test.go:392
            	Error:      	Received unexpected error:
            	            	pool.With failed with 1 attempts: non-retryable error occurred on attempt No.1 (idempotent=false): context canceled at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.execute(execute_query.go:158)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.(*Session).execute(session.go:176)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.(*Session).queryRow(session.go:70)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.clientQueryRow.func1(client.go:330)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.do.func1(client.go:224)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/pool.(*Pool).try(pool.go:490)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/pool.(*Pool).With.func2(pool.go:518)` at `github.com/ydb-platform/ydb-go-sdk/v3/retry.Retry.func1(retry.go:264)` at `github.com/ydb-platform/ydb-go-sdk/v3/retry.opWithRecover(retry.go:418)` at `github.com/ydb-platform/ydb-go-sdk/v3/retry.RetryWithResult(retry.go:358)` at `github.com/ydb-platform/ydb-go-sdk/v3/retry.Retry(retry.go:270)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/pool.(*Pool).With(pool.go:524)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.do(client.go:232)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.clientQueryRow(client.go:336)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/query.(*Client).QueryRow(client.go:362)`
            	Test:       	TestBasicExampleQuery/ExecuteDataQuery
    basic_example_query_test.go:47: total consumed units: 40
    mutex.go:15: 
    ```

File: internal/query/execute_query.go [hunk 5]
```diff
@@ -138,7 +140,28 @@ func execute(
...
+	// propagate the cancellation to executeCtx during the blocking Recv call.
+	select {
+	case <-ctx.Done():
+		if xcontext.IsIdempotent(ctx) {
+			return nil, xerrors.WithStackTrace(xerrors.Retryable(
+				ctx.Err(),
+				xerrors.WithName("streamResultContext"),
+			))
+		}
+		return nil, xerrors.WithStackTrace(ctx.Err())
```
Comment (asmyasnikov) [inline internal/query/execute_query.go]:
```suggestion

		return nil, xerrors.WithStackTrace(ctx.Err())
```

**Review by asmyasnikov — APPROVED** [review]
